name: Test policy file

on:
  push:
    branches:
      - main

jobs:
  test_policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Open Policy Agent v0.28.0
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.28.0/opa_linux_amd64
          chmod 755 opa

      - name: Test generated policy
        run: ./opa test policy
